name: mobilbox
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_bloc: ^3.2.0
  bloc: ^3.0.0
  rxdart: ^0.23.1
  equatable: ^1.0.0
  flutter_svg: ^0.22.0
  eva_icons_flutter: ^2.0.0
  font_awesome_flutter: ^8.5.0
  page_indicator: ^0.2.0
  flutter_secure_storage: ^3.3.1
  expand_widget: ^0.2.0+2
  flutter_html: ^0.11.1
  animations: ^1.0.0+5
  url_launcher: ^6.0.12
  cached_network_image: ^2.0.0
  flutter_datetime_picker: ^1.3.5
  flutter_launcher_icons: ^0.9.2
  pin_code_text_field: ^1.5.1
  dio: ^4.0.0
  liquid_pull_to_refresh: ^1.1.1
  webview_flutter: ^1.0.7
  # background_location: ^0.6.1
  flutter_map: ^0.11.0
  location: ^4.3.0
  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      - assets/images/boxlogo.jpg
      - assets/images/qpay_qr.png
      - assets/images/police.png
      - assets/icons/police.svg
      - assets/icons/insurance.svg
      - assets/icons/money.svg
      - assets/icons/patient.svg
      - assets/icons/usb.svg
      - assets/icons/transfer.svg
      - assets/icons/document.svg
      - assets/icons/phone.svg
      - assets/operators/unitel.png
      - assets/operators/skytel.png
      - assets/operators/gmobile.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
